// <auto-generated> Generated from Quill/Shaders/Canvas.slang by Quill.ShaderGen. Do not edit.
//
// Matrix convention: Slang emits mul(M, v) as v * M, so every mat4 uniform here must be
// uploaded transposed (glUniformMatrix4fv with transpose = true) relative to the matrix the
// canvas hands the backend. Same bytes as before, flipped flag.
Shader "Quill/Blur"
{
    Pass
    {
        Name "Blur"

        Cull Off
        ZTest Disabled
        Blend One InverseSourceAlpha

        SLANGPROGRAM
        import VariantAttributes;

        [VariantAxis]
        extern static const bool Upsample;
        // This file is part of the Prowl Game Engine
        // Licensed under the MIT License. See the LICENSE file in the project root for details.
        //
        // Dual Kawase backdrop blur, the second half of the single source of truth for Quill's shaders.
        // Every backend's blur shader is generated from this file by Quill.ShaderGen on build.


        import UVOrigin;

        uniform Sampler2D src;
        uniform float2 halfpixel; // half a texel of the basis surface
        uniform float offset;     // sample spread, i.e. blur strength

        struct BlurVaryings
        {
            float4 position : SV_Position;
            float2 vUV : TEXCOORD0;
        };


        // Fullscreen triangle; needs no vertex buffer.
        [shader("vertex")]
        BlurVaryings Vertex(uint vertexIndex : SV_VertexID)
        {
            BlurVaryings output;
            float2 p = float2(float((vertexIndex << 1) & 2), float(vertexIndex & 2));
            // p is bottom-left relative (matches the standard clip-space Y the backend's viewport transform
            // produces), so top-left-origin backends need their V flipped to sample the right way up.
            output.vUV = IsUVOriginTopLeft ? float2(p.x, 1.0 - p.y) : p;
            output.position = float4(p * 2.0 - 1.0, 0.0, 1.0);
            return output;
        }


        // Samples the higher-resolution source into a half-size target.
        float4 BlurDownsample(BlurVaryings input) : SV_Target
        {
            float2 uv = input.vUV;
            float4 sum = src.Sample(uv) * 4.0;
            sum += src.Sample(uv - halfpixel * offset);
            sum += src.Sample(uv + halfpixel * offset);
            sum += src.Sample(uv + float2(halfpixel.x, -halfpixel.y) * offset);
            sum += src.Sample(uv - float2(halfpixel.x, -halfpixel.y) * offset);
            return sum / 8.0;
        }


        // Samples the lower-resolution source into a double-size target.
        float4 BlurUpsample(BlurVaryings input) : SV_Target
        {
            float2 uv = input.vUV;
            float4 sum = src.Sample(uv + float2(-halfpixel.x * 2.0, 0.0) * offset);
            sum += src.Sample(uv + float2(-halfpixel.x, halfpixel.y) * offset) * 2.0;
            sum += src.Sample(uv + float2(0.0, halfpixel.y * 2.0) * offset);
            sum += src.Sample(uv + float2(halfpixel.x, halfpixel.y) * offset) * 2.0;
            sum += src.Sample(uv + float2(halfpixel.x * 2.0, 0.0) * offset);
            sum += src.Sample(uv + float2(halfpixel.x, -halfpixel.y) * offset) * 2.0;
            sum += src.Sample(uv + float2(0.0, -halfpixel.y * 2.0) * offset);
            sum += src.Sample(uv + float2(-halfpixel.x, -halfpixel.y) * offset) * 2.0;
            return sum / 12.0;
        }


        [shader("fragment")]
        float4 Fragment(BlurVaryings input) : SV_Target
        {
            static if (Upsample)
                return BlurUpsample(input);

            return BlurDownsample(input);
        }
        ENDSLANG
    }
}
