<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>disable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <Optimize>true</Optimize>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
        <TieredPGO>true</TieredPGO>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Graphite\Prowl.Graphite.csproj" />
        <ProjectReference Include="..\..\ShaderDef\Core\Prowl.Graphite.ShaderDef.csproj" />
        <ProjectReference Include="..\..\ShaderDef\Compiler\Prowl.Graphite.ShaderDef.Compiler.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Shaders/**/*" />
        <Content Include="Shaders/**/*" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
